pypro/base/urls.py
from django.urls import path

from pypro.base.views import home

app_name = 'base'
urlpatterns = [
    path('', home, name='home'),
]

pypro/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pypro.base.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(
        path('__debug__/', include(debug_toolbar.urls))
    )

pypro/base/models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.core.mail import send_mail
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given email and password.
        """
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_staff', True)

        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """
    App base user class.

    Email and password are required. Other fields are optional.
    """

    first_name = models.CharField(_('first name'), max_length=150, blank=True)
    email = models.EmailField(_('email address'), unique=True)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = '%s' % (self.first_name)
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

pypro/base/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'base/home.html')

pypro/base/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}Python Pro{% endblock title %}</title>

    <meta name="description" content="Pagina do Curso Python Pro">
    <meta name="author" content="Raol Brito">
    <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}" />
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/scripts.js' %}"></script>

  </head>
  <body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
   <a class="navbar-brand" href="{% url 'base:home' %}">Python Pro</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

    </ul>
  </div>
</nav>

  {% block body %}{% endblock body %}
    <div class="container">
	<div class="row">
		<div class="col-md-12">

			<div class="jumbotron">
				<h2>
					Curso de Python RaolBrito, Python Pro!
				</h2>
                <h4 class="mt-2"> Entre na fila de espera</h4>

<form action="https://raolpython.us2.list-manage.com/subscribe/post?u=a2048027246c2b08a53ddfa5c&amp;id=3ee23ad24f"
      method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form"
      class="form-row align-items-center" target="_blank" novalidate>
  <div class="form-row align-items-center">

    <div>
      <label class="sr-only" for="mce-EMAIL">Email</label>
        <label for="mce-EMAIL"></label>
        <input type="email" value="" name="EMAIL" class="form-control required" id="mce-EMAIL" placeholder="exemplo@email.com">
    </div>
      <div class="mt-4">
         <label class="sr-only" for="mce-FNAME">Email</label>
         <input  type="text" value="" name="FNAME" class="form-control" id="mce-FNAME" placeholder="Seu Nome">
        </div>
              <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><label>
        <input class="mt-2" type="text" name="b_a2048027246c2b08a53ddfa5c_3ee23ad24f" tabindex="-1" value="">
    </label></div>
      <div class="mt-4 ml-2">
        <input type="submit" value="Salvar" name="subscribe" id="mc-embedded-subscribe" class="btn btn-primary">
    </div>
  </div>
</form>

			</div>
			<div class="row">
				<div class="col-md-12">
					<div class="card">
						<h5 class="card-header">
							Mais detalhes sobre o estudante
						</h5>
						<div class="card-body">
							<p class="card-text">
								<img src="{% static 'img/rb.png' %}" alt="foto de Rafael Brito"
                                     class="img-thumbnail float-left mr-3"/>
                                Rafael Brito é estudante de Data Science e Desenvolvimento Backend
                                 <a href="https://www.python.pro.br/" target="_blank" > Pyhton Pro Br</a>
                                com base na linguagem Python e Framework Django, atualmente trabalha
                                como Projetista de Tubulações industriais mas espera em breve conseguir
                                migrar para a area de desenvolvimento, atualmente cursa Python Pro Br
                                onde tem descoberto novas ferramentas e funções nesse imenso mundo da programação.

							</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

  <footer class="main-footer mt-5 pt-4 text-light">
      <div class="container">
          <div class="row">
              <div class="col">

              </div>
          </div>
      </div>
          <div class="container">
          <div class="row">
              <div class="col">
                  <h3>Entre em contato</h3>
                  <address>
                    +55 21 98080-2294
                    <br/>
                    <a href="mailto:ra.brito@yahoo.com.br">ra.brito@yahoo.com.br</a>
                  </address>
              </div>
          </div>
      </div>
      <div class="rights pb-4">
       <div class="container">
          <div class="row">
              <div class="col">
                  {% now 'Y' %} Python Pro. Todos direitos reservados
              </div>
          </div>
       </div>
      </div>
  </footer>

  </body>
</html>

pypro/base/templates/base/home.html
{% extends 'base/base.html' %}
{% load static %}

<title>{% block title %}Python Pro - Home{% endblock title %}</title>

{% block body %}
    <div class="container">
	<div class="row">
		<div class="col-md-12">

			<div class="jumbotron">
				<h2>
					Curso de Python RaolBrito, Python Pro!
				</h2>
                <h4 class="mt-2"> Entre na fila de espera</h4>

<form action="https://raolpython.us2.list-manage.com/subscribe/post?u=a2048027246c2b08a53ddfa5c&amp;id=3ee23ad24f"
      method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form"
      class="form-row align-items-center" target="_blank" novalidate>
  <div class="form-row align-items-center">

    <div>
      <label class="sr-only" for="mce-EMAIL">Email</label>
        <label for="mce-EMAIL"></label>
        <input type="email" value="" name="EMAIL" class="form-control required" id="mce-EMAIL" placeholder="exemplo@email.com">
    </div>
      <div class="mt-4">
         <label class="sr-only" for="mce-FNAME">Email</label>
         <input  type="text" value="" name="FNAME" class="form-control" id="mce-FNAME" placeholder="Seu Nome">
        </div>
              <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><label>
        <input class="mt-2" type="text" name="b_a2048027246c2b08a53ddfa5c_3ee23ad24f" tabindex="-1" value="">
    </label></div>
      <div class="mt-4 ml-2">
        <input type="submit" value="Salvar" name="subscribe" id="mc-embedded-subscribe" class="btn btn-primary">
    </div>
  </div>
</form>

			</div>
			<div class="row">
				<div class="col-md-12">
					<div class="card">
						<h5 class="card-header">
							Mais detalhes sobre o estudante
						</h5>
						<div class="card-body">
							<p class="card-text">
								<img src="{% static 'img/rb.png' %}" alt="foto de Rafael Brito"
                                     class="img-thumbnail float-left mr-3"/>
                                Rafael Brito é estudante de Data Science e Desenvolvimento Backend
                                 <a href="https://www.python.pro.br/" target="_blank" > Pyhton Pro Br</a>
                                com base na linguagem Python e Framework Django, atualmente trabalha
                                como Projetista de Tubulações industriais mas espera em breve conseguir
                                migrar para a area de desenvolvimento, atualmente cursa Python Pro Br
                                onde tem descoberto novas ferramentas e funções nesse imenso mundo da programação.

							</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock body %}